org: akerpelm
app: serverless-test-api-v2
service: serverless-rest-api-project
frameworkVersion: "2 || 3"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: "20201221"
  region: us-east-1
  iamRoleStatements: # all Lambda functoins can perform all actions.
    - Effect: Allow
      Action:
        - dynamodb:* #not best practice likely
      Resource:
        - arn:aws:dynamodb:us-east-1:498741492800:table/TodoTable

functions:
  addTodo:
    handler: src/addTodo.handler
    events:
      - httpApi:
          path: /todos
          method: post
  fetchTodos:
    handler: src/fetchTodos.handler
    events:
      - httpApi:
          path: /todos
          method: get
  fetchTodo:
    handler: src/fetchTodo.handler
    events:
      - httpApi:
          path: /todos/{id}
          method: get
  updateTodo:
    handler: src/updateTodo.handler
    events:
      - httpApi:
          path: /todos/{id}
          method: patch

# Create table through infrastructure as code approach
resources:
  Resources: # CloudFormation to define our resources
    TodoTable: # assign type
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TodoTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions: #define attribute for p_key
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id # attribute to p_key.
            KeyType: HASH
